In [2]:
import numpy as np

# Fitbit

In [3]:
data = np.loadtxt('fit.txt', dtype='str')

In [4]:
data.shape

(96, 6)

In [5]:
data.ndim

2

We have 96 rows and 6 columns in the data

There 96 rows, represent 96 days

In [6]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [7]:
data[1]

array(['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'], dtype='<U10')

In [8]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [9]:
data_t = data.T

In [10]:
data_t.shape

(6, 96)

In [11]:
len(data_t)

6

In [12]:
dates = data_t[0]
dates

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [13]:
step_count = data_t[1]
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [14]:
step_count = np.array(step_count, dtype="int") # Force the datatype of integer on this

In [15]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [16]:
step_count.mean()

2935.9375

In [75]:
data.shape

(96, 6)

In [35]:
# For step count
# Row condition: all rows
# Column condition: col 1
step_count = data[:, 1]

In [17]:
step_count = np.array(step_count, dtype="int")
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [38]:
# For mood
# Row condition: all rows
# Column condition: col 2
mood = data[:, 2]
mood 
#step_count

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [45]:
step_count_happy = step_count[mood=="Happy"]
step_count_happy

array(['4732', '330', '4550', '4435', '4779', '1831', '2255', '539',
       '5464', '4068', '4683', '4033', '6314', '614', '3149', '4005',
       '4880', '4136', '705', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '3608', '774', '1421', '4064', '2725',
       '5934', '1867', '7422', '5537', '5376', '153', '2203'],
      dtype='<U10')

In [43]:
len(step_count_happy)

40

In [28]:
step_count_sad = step_count[mood=="Sad"]

In [29]:
len(step_count_sad)

29

In [30]:
step_count_neutral = step_count[mood=="Neutral"]
len(step_count_neutral)

27

In [31]:
step_count_happy_or_neutral = step_count[(mood=="Happy") | (mood=="Neutral")]
len(step_count_happy_or_neutral)

67

In [32]:
step_count_happy.mean()

3392.725

In [33]:
step_count_neutral.mean()

3153.777777777778

In [34]:
step_count_sad.mean()

2103.0689655172414

# Numpy basics

## Shape and indexing

In [9]:
a = np.array(range(16))

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
a = a.reshape(8, 2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [15]:
len(a)

8

In [16]:
a[0]

array([0, 1])

In [17]:
a[6]

array([12, 13])

In [19]:
# a[8] # This will give me an error

In [20]:
a = np.array(range(16))

In [24]:
# a.reshape(10, 2) #Error

In [22]:
a.reshape(2, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [26]:
a = a.reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
a.shape

(4, 4)

In [34]:
a = a.reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
a[1]

array([4, 5, 6, 7])

In [36]:
a[1, 2] # 2nd row, 3rd column

6

In [37]:
a.ndim

2

## Transpose

In [39]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a.shape

(3, 4)

In [42]:
b = a.T # Transpose of a
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [43]:
b.shape

(4, 3)

## Indexing and slicing

In [59]:
m1 = np.arange(1,10).reshape((3,3))
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
m1[1]

array([4, 5, 6])

In [61]:
m1[1][1]

5

In [62]:
m1[1, 1]

5

In [64]:
m1 = np.array([100,200,300,400,500,600])
m1

array([100, 200, 300, 400, 500, 600])

In [65]:
m1[[2,3,4,1,2,2]]

array([300, 400, 500, 200, 300, 300])

In [66]:
m1 = np.arange(9).reshape((3,3))
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
m1[[0, 1, 2],[0, 1, 2]]

array([0, 4, 8])

In [68]:
m1 = np.arange(12).reshape(3,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
m1[0:2] # last element is excluded. This gives row 0 and row 1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [70]:
# I want ALL rows ":", but 0th and 1st column only "0:2"
m1[: , 0:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [71]:
# Row condition: all rows ":"
# Column condition: column 1 and column2 
m1[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [73]:
# Row condition: all rows ":"
# Column condition: only column 2 "2"
m1[:, 2:3]

array([[ 2],
       [ 6],
       [10]])

In [74]:
# Row condition: row 0 and row1, "0:2"
# Column conditin: col 1 and col2, "1:3"
m1[0:2, 1:3]


array([[1, 2],
       [5, 6]])

## Masking

In [84]:
m1 = np.arange(12).reshape(3, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
m1 < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [86]:
m1[m1 < 6]

array([0, 1, 2, 3, 4, 5])

In [88]:
s = np.array([300, 457, 2000, 430, 3500])
s

array([ 300,  457, 2000,  430, 3500])

In [96]:
s[ [False, False, True, True, True] ] # One way to get the last 3 elements

array([2000,  430, 3500])

In [92]:
m = np.array(["sad", "sad", "happy", "happy", "happy"])
m

array(['sad', 'sad', 'happy', 'happy', 'happy'], dtype='<U5')

In [93]:
m == "happy"

array([False, False,  True,  True,  True])

In [115]:
s[m=="happy"]

array([2000,  430, 3500])

## Aggregate functions / Reduction

In [116]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [117]:
arr.sum()

3

In [118]:
arr.mean()

1.0

In [119]:
arr.min() # smallest

0

In [120]:
arr.max()

2

In [121]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.sum(a)

66

In [123]:
np.sum(a, axis=0) # column wise sum

array([12, 15, 18, 21])

In [124]:
np.sum(a, axis=1) # row wise sum

array([ 6, 22, 38])

In [125]:
np.mean(a)

5.5

In [126]:
np.mean(a, axis=0) # column mean

array([4., 5., 6., 7.])

In [127]:
np.mean(a, axis=1) # row mean

array([1.5, 5.5, 9.5])

In [ ]:
# Homework: Try the same with min, max, with "axis". 

## Logical 

In [128]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

In [129]:
a

array([1, 2, 3, 4])

In [130]:
b

array([4, 3, 2, 1])

In [131]:
np.any(a<b) # Atleast 1 element in a < corresponding element in b

True

In [132]:
a = np.array([4,5,6,7])
b = np.array([4,3,2,1])
np.any(a<b)

False

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

In [133]:
np.all(a<b)

False

In [134]:
a = np.array([1,0,0,0])
b = np.array([4,3,2,1])
np.all(a<b)

True

In [135]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
# output: [-1, 1, 1, 1, -1, 1, -1, -1, 1, 1] "Indicate the sign of the value"
# Wherever <0 replace with -1
# Wherever >=0 replace with 1

In [137]:
np.where(arr >= 0, 1, -1)

array([-1,  1,  1,  1, -1,  1, -1, -1,  1,  1])

In [138]:
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [140]:
np.where(arr>0, "pos", "neg")

array(['neg', 'pos', 'pos', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos',
       'neg'], dtype='<U3')

In [70]:
arr = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [4, 8, 9],
 [7, 8, 9],
 [4, 8, 9]]
 )
odd_row_array = arr[::2,:]

odd_row_array.flatten()

array([1, 2, 3, 7, 8, 9, 7, 8, 9])

In [67]:
arr[::-1,::-1]

array([[9, 8, 4],
       [9, 8, 7],
       [9, 8, 4],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [75]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
mat_T = mat.T
mat_T[:,::-1]

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [83]:
import numpy as np
arr = 2*np.arange(0,2,0.5)
print(arr)
if np.all(arr<=0.6):
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy") 

[0. 1. 2. 3.]
condition doesn't satisfy


In [89]:
import numpy as np
X = np.arange(12).reshape(3,4)
X.max(axis=1)
X.sum()


66

In [164]:
d = np.array([[5,3,9],[2,3,4],[7,3,8]])
mask = d[:,1].argsort()
d[mask]





array([[7, 1, 8],
       [5, 3, 9],
       [2, 3, 4]])