In [1]:
import numpy as np

In [2]:
arr = np.arange(12)


In [3]:
a = arr.reshape(-1, 4)

In [4]:
a.shape

(3, 4)

In [5]:
# b = arr.reshape(-1, 8) Error

In [6]:
A = np.arange(10).reshape(5,2)
A.shape

(5, 2)

In [7]:
B = np.arange(2).reshape(2,1)
B.shape

(2, 1)

In [8]:
np.dot(A, B).shape

(5, 1)

## Split

In [9]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [11]:
np.split(x, [3, 5, 6])

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]

In [12]:
np.split(x, [3, 7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8])]

In [13]:
"hsplit" "vsplit"

'hsplitvsplit'

In [14]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [15]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [16]:
np.hsplit(x, [1, 4])

[array([[ 0.],
        [ 4.],
        [ 8.],
        [12.]]),
 array([[ 1.,  2.,  3.],
        [ 5.,  6.,  7.],
        [ 9., 10., 11.],
        [13., 14., 15.]]),
 array([], shape=(4, 0), dtype=float64)]

In [17]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [18]:
np.vsplit(x, [1, 3])

[array([[0., 1., 2., 3.]]),
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]])]

## Stacking

In [19]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [20]:
np.vstack((data, data, data)) # Vertical stack

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [21]:
data = np.arange(5).reshape(5,1)
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [22]:
np.hstack( (data, data, data) )

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [23]:
a = np.array([[1], [2], [3]])
a

array([[1],
       [2],
       [3]])

In [24]:
a.shape

(3, 1)

In [25]:
b = np.array([[4], [5], [6]])
b 

array([[4],
       [5],
       [6]])

In [26]:
b.shape

(3, 1)

In [27]:
c = np.hstack((a, b))
c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
c.shape

(3, 2)

In [29]:
d = np.vstack((a, b))
d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [30]:
d.shape

(6, 1)

# Concatenate

In [31]:
z = np.array([[2, 4]])
z

array([[2, 4]])

In [32]:
z.shape

(1, 2)

In [33]:
np.concatenate([z, z], axis=0) #axis=0 --> vstack

array([[2, 4],
       [2, 4]])

In [34]:
np.concatenate([z, z], axis=1) #axis=1 --> hstack

array([[2, 4, 2, 4]])

In [35]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [36]:
a.shape

(2, 2)

In [37]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [38]:
b.shape

(1, 2)

In [39]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
#np.concatenate((a, b), axis=1) # Will horizontal stacking work?

In [41]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

# Broadcasting

In [42]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [43]:
# tile
np.tile(a, (3, 1))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [44]:
np.tile(a, (3, 2)) # combination of v and h stack

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [45]:
a = np.tile(a, (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [46]:
b = np.tile(np.arange(0,3), (4,1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [47]:
b.shape

(4, 3)

In [48]:
a + b # element wise addition

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [49]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [50]:
a.shape

(4, 3)

In [51]:
b = np.arange(0,3)
b

array([0, 1, 2])

In [52]:
b.shape

(3,)

In [53]:
a + b # Example of broadcast

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [54]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [55]:
a = a.reshape(4,1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [56]:
a.shape

(4, 1)

In [57]:
b = np.arange(0,3)
b

array([0, 1, 2])

In [58]:
b.shape

(3,)

In [59]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [60]:
a * b

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

In [61]:
a = np.arange(12).reshape(4, 3)
a.shape

(4, 3)

In [62]:
b = np.arange(3)
b.shape 

(3,)

In [63]:
a + b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [64]:
c = np.arange(3).reshape(1, 3)
c.shape

(1, 3)

In [65]:
c

array([[0, 1, 2]])

In [66]:
a + c

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [67]:
a * c

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16],
       [ 0, 10, 22]])

In [68]:
d = np.arange(3).reshape(3, 1)

In [69]:
d

array([[0],
       [1],
       [2]])

In [70]:
# a + d

In [71]:
# a * d

In [72]:
e = np.arange(4).reshape(4, 1)

In [73]:
a + e

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [74]:
a * e

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [27, 30, 33]])

In [75]:
f = np.arange(8).reshape(4, 2)

In [76]:
# a + f

In [77]:
# a * f

In [78]:
x = np.arange(60).reshape(5, 4, 3)

In [79]:
x.shape

(5, 4, 3)

In [80]:
len(x)

5

In [81]:
x[0].shape

(4, 3)

In [82]:
len(x[0])

4

In [83]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [84]:
x[1]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [85]:
x[2]

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [86]:
x[0:3].shape # Give me 0th, 1st and 2nd object in x

(3, 4, 3)

In [87]:
x[0:3]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [88]:
np.split(x, [3])

[array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],
 
        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]),
 array([[[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]],
 
        [[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]])]

In [89]:
np.split(x, [2, 3])

[array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]]),
 array([[[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]),
 array([[[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]],
 
        [[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]])]

In [90]:
x[0:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [91]:
x[2:3]

array([[[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [92]:
x[3:]

array([[[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [96]:
images = np.arange(10*19*25*3).reshape(10, 19, 25, 3) # Imagine 10 images of 5MP

In [101]:
batches = np.split(images, [3, 5, 6, 8])

In [102]:
len(batches)

5

# Dimension expansion and reduction

In [103]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [104]:
arr.shape

(6,)

In [105]:
arr = arr.reshape(1, -1)
arr.shape

(1, 6)

In [109]:
arr

array([[0, 1, 2, 3, 4, 5]])

In [106]:
arr1 = np.expand_dims(arr, axis = 0 )
arr1

array([[[0, 1, 2, 3, 4, 5]]])

In [107]:
arr1.shape

(1, 1, 6)

In [108]:
arr1

array([[[0, 1, 2, 3, 4, 5]]])

In [110]:
a = np.arange(12).reshape(4, 3)
a.shape

(4, 3)

In [116]:
np.expand_dims(a, axis=2).shape

(4, 3, 1)

In [117]:
arr = np.arange(9).reshape(1,1,9)
arr

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]])

In [118]:
arr.shape

(1, 1, 9)

In [119]:
arr1 = np.squeeze(arr)
arr1.shape

(9,)

In [120]:
arr1 = np.squeeze(arr, axis = 1 )
arr1

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [121]:
arr1.shape

(1, 9)

In [123]:
# np.squeeze(arr, axis = 2 ) # This value is not 1 in the shape. It is 9

In [131]:
# Dice
np.random.choice([1, 2, 3, 4, 5, 6])

5

In [143]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
a[[True, True, True, False,False, False,False, False,False, False ]]

array([0, 1, 2])

In [137]:
a[0:3]

array([0, 1, 2])

In [147]:
a = np.array([0, 2, 5, 1, 3])

In [148]:
args_a = np.argsort(a)

In [150]:
args_a

array([0, 3, 1, 4, 2])

In [156]:
a[[4, 4, 4, 4, 3, 2]]

array([3, 3, 3, 3, 1, 5])

In [149]:
a[args_a[0:2]]

array([0, 1])

In [142]:
np.sort(a)

array([0, 1, 2, 3, 5])

In [161]:
a = np.arange(12).reshape(1, 12)

In [164]:
a.shape

(1, 12)

In [162]:
b = np.arange(60).reshape(12, 5)

In [165]:
b.shape

(12, 5)

In [163]:
np.dot(a, b)

array([[2530, 2596, 2662, 2728, 2794]])

In [166]:
np.dot(b, a)

ValueError: shapes (12,5) and (1,12) not aligned: 5 (dim 1) != 1 (dim 0)

In [176]:
a = np.arange(9)

In [180]:
a.shape

(9,)

In [177]:
b = np.arange(9).reshape(9, 1)

In [181]:
b.shape

(9, 1)

In [179]:
np.dot(a,b)

array([204])

In [191]:
import matplotlib.pyplot as plt
import cv2
img = np.array(plt.imread('fruits.png'))

In [192]:
img.shape

(1333, 2000, 3)

In [195]:
img.flatten()[0:6]

array([0.8784314, 0.9137255, 0.972549 , 0.8784314, 0.9137255, 0.972549 ],
      dtype=float32)

In [194]:
img[0, 0, 0:3]

array([0.8784314, 0.9137255, 0.972549 ], dtype=float32)

In [196]:
img[0, 1, 0:3]

array([0.8784314, 0.9137255, 0.972549 ], dtype=float32)

In [ ]:
img[:, :, 0]