In [ ]:
# Most important operation is matrix multipication for image computaion





In [3]:
import numpy as np
arr = np.arange(12)

In [8]:
a = arr.reshape(-1,4)
a.shape

(3, 4)

In [12]:
b= np.arange(2).reshape(2,1)
print(b)
b.shape

[[0]
 [1]]


(2, 1)

In [13]:
# We would want to only take a part of the array
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.split(x,3) #Splits the array into 3 parts

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [15]:
# Splitting based on unequal distribution
np.split(x,[3,5,6]) #Specify the loacation (not index) and cut the numpy array there

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]

In [17]:
x = np.arange(16.0).reshape(4,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [20]:
np.hsplit(x,2) #Split horizintal
# Left and right Horizontal

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [19]:
np.vsplit(x,2) #Certical horizintal 
# Up and down Vertical

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [21]:
np.hsplit(x,[3,6])

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]]),
 array([], shape=(4, 0), dtype=float64)]

In [22]:
np.vsplit(x,[1,3])

[array([[0., 1., 2., 3.]]),
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]])]

# Stacking

In [24]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [25]:
np.vstack([data,data,data]) #Vertical stack 1 below the other

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [27]:
data = np.arange(5).reshape(5,1)
np.hstack((data,data,data)) #Vertical stack 1 below the other

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [32]:
a = np.array([[1],[2],[3]])
a

b = np.array([[4],[5],[6]])
b

array([[4],
       [5],
       [6]])

In [34]:
c = np.hstack((a,b))
c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
c.shape

(3, 2)

In [37]:
d = np.vstack((a,b))
d.shape

(6, 1)

In [40]:
# Concat
z = np.array([[2,4]])
z

array([[2, 4]])

In [41]:
z.shape

(1, 2)

In [42]:
np.concatenate(z,z,axis=1)

TypeError: concatenate() got multiple values for argument 'axis'

In [47]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [49]:
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis. We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking. We pass a sequence of arrays that we want to join to the stack() method along with the axis.

# Braodcasting

In [64]:

a = np.arange(0,40,10)

In [65]:
# tile

# We want to get the numbers to stack onto each other giving more rows

np.tile(a,(3,1)) 

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [62]:
np.tile(a,(3,2)) #Combination of v and h stack

array([[ 0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30],
       [ 0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30],
       [ 0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30]])

In [66]:
a = np.tile(a, (3,1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [68]:
b = np.tile(np.arange(0,3),(4,1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [69]:
b.shape

(4, 3)

In [70]:
a + b #Element wise addition

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [71]:
a 

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [72]:
a.shape

(4, 3)

In [74]:
b = np.arange(0,3)
b

array([0, 1, 2])

In [75]:
b.shape

(3,)

In [77]:
a + b  #It broadcasts the missing shape

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [93]:
a = np.arange(0,40,10)
a = a.reshape([4,1])
a.shape

(4, 1)

In [94]:
b = np.arange(0,3)
b.shape

(3,)

In [96]:
a + b #Both rows get broadcasted to total rows and columns get broadcasted to total columns

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [99]:
a = np.arange(12).reshape(4,3)
a.shape

(4, 3)

In [101]:
b = np.arange(3)
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [103]:
c = np.arange(3).reshape(1,3)
c.shape

(1, 3)

In [104]:
a + c

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [106]:
d = np.arange(3).reshape(3,1)
d
#4,3 with 1,3 you can
#4,3 with 3,1 you canot broadcast


array([[0],
       [1],
       [2]])

In [107]:
a +d #Throws an error

ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

In [108]:
e = np.arange(4).reshape(4,1) 
a+e #4x3 and 4x1 it can be broadcasted

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [110]:
# At least 1 dimension should be 1 and at least one dimension must match in an 2d broadcasting

f = np.arange(8).reshape(4,2)
a +f 

ValueError: operands could not be broadcast together with shapes (4,3) (4,2) 

In [111]:
a * c
#Element wise multiplication

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16],
       [ 0, 10, 22]])

In [114]:
# 3 D arrays

x = np.arange(60).reshape(5,4,3)
len(x) # First dimension is length


5

In [115]:
x.shape
# 5 objects of 4x3

(5, 4, 3)

In [117]:
x[0].shape #Similar to this there are 5 of these
#Each objecct is 4x3 matrix
len(x[0])

4

In [120]:
x[0:3] #X has 5 objects , we want 0, 1st and 2nd object 
x[0:3].shape

(3, 4, 3)

In [121]:
np.split(x,[3]) #First cut is at 3 and Second cut from 4 and 5

[array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],
 
        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]),
 array([[[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]],
 
        [[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]])]

In [123]:
np.split(x,[2,3]) #First cut is at 2 and Second cut at 3 and rest 4 and 5

[array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]]),
 array([[[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]),
 array([[[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]],
 
        [[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]])]

In [131]:
images = np.arange(10*19*25*3).reshape(10,19,25,3) #Image 10 images of 5 MP
batches = np.split(images, [3,5,6,8])
len(batches)

5

# Dimenarion expansion and reduction

In [133]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [134]:
arr.shape

(6,)

In [136]:
arr = arr.reshape(1,-1) # We addrd a dimension
arr.shape 

(1, 6)

In [142]:
print(arr.shape)
arr1 = np.expand_dims(arr,axis=0) #At 0th location put a 1
print(arr1.shape)
arr1

(1, 6)
(1, 1, 6)


array([[[0, 1, 2, 3, 4, 5]]])

In [139]:
arr1.shape #Expand dimension and put a one on the axis mentioned

(1, 1, 6)

In [143]:
arr1

array([[[0, 1, 2, 3, 4, 5]]])

In [144]:
a = np.arange(12).reshape(4,3)
a.shape

(4, 3)

In [146]:
np.expand_dims(a,axis=2).shape #On that axis or that dimension we get a new dimension

(4, 3, 1)

In [148]:
arr =np.arange(9).reshape(1,1,9)
arr.shape # We have fake dimesnions we are ok with (9,)

(1, 1, 9)

In [151]:
arr1 = np.squeeze(arr)
arr1.shape

(9,)

In [153]:
arr1 = np.squeeze(arr,axis=1) #Kill the dimension mentioned in the axis
arr1.shape

(1, 9)

In [155]:
# We can't squeeze an non 1 dimension
np.squeeze(arr,axis=2) #Throws erroe

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [158]:
np.random.choice([1,2,3,4,5,6])

5

In [160]:
# SHALLOW COPY VS DEEP COPY
import numpy as np
a = np.arange(4)
a

array([0, 1, 2, 3])

In [161]:
b = a.reshape((2,2))
b

array([[0, 1],
       [2, 3]])

In [162]:
#Shallow copy
a[0]=100 #If we change a[0] value to 100 b[0] is changed too, since we rehaped values from a and put it to b

In [164]:
b
np.shares_memory(a,b)
# If it's true they are accessing the same memory

True

In [173]:

a= np.arange(4)
c = a+2

In [174]:
c

array([2, 3, 4, 5])

In [178]:
a[0] = 100 
print(c)
np.shares_memory(a,c) #They don't share the same memory location now

[2 3 4 5]


False

In [181]:
a= np.arange(4)
b = a.copy() #deep_copy
b

array([0, 1, 2, 3])

In [190]:
c = np.array([1,"m",[1,2,3]],dtype=object)
print(c)
d =c.copy()
print(d) 
#Notice both the output is same

[1 'm' list([1, 2, 3])]
[1 'm' list([1, 2, 3])]


In [193]:
c[2][0] = 100
print(c)
d #Here d is also changed, which means deep copy failed

[1 'm' list([100, 2, 3])]


array([1, 'm', list([100, 2, 3])], dtype=object)

In [200]:
# More relaible approach to copy is 
import copy
c = np.array([1,"m",[1,2,3]],dtype=object)
print(c)
d=copy.deepcopy(c)
d

[1 'm' list([1, 2, 3])]


array([1, 'm', list([1, 2, 3])], dtype=object)

In [201]:
view_a = a.view()
view_a

array([0, 1, 2, 3])

In [202]:
a[2] = 100

In [203]:
view_a

array([  0,   1, 100,   3])

In [204]:
np.shares_memory(a,view_a)

True