# Basics

In [6]:
import numpy as np

In [9]:
# What is the most basic structute in Python?
# Ans: List
a = [1,2,3,4,5]
#Print squares in a (List comprehension)
b = [i**2 for i in a ]

[1, 4, 9, 16, 25]

In [20]:
# If we  want to do the same thing in numpy, i.e squares of two numbers
# We use np.array
# Type of it is numpy.ndarray
a = np.array([1,2,3,4,5])
type(a)
print(a)

[1 2 3 4 5]


In [23]:
#Range of variables
list(range(10))
#lets say n has a huge range
l = range(1000000)
#%timeit will run it 7 times and find a mean+ srd_dev
%timeit [i**2 for i in l]


182 ms ± 1.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
#Let's time it in numpy
#Instead of range we use arange
a = np.arange(10)
l = np.arange(1000000)
#We need not write a list comprehensition like we did for a list, we do have a power function for numpy arrays
%timeit l**2
#AS we see the output it's much faster (milli to micro)

551 µs ± 27.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
#The reason why it is fast is , getting the items takes time
# A list and np.array diiference is 
# Stores in c_arrays under the hood 

# Arange

In [26]:
arr2 = np.arange(1,5) #last element is excluded
arr2

array([1, 2, 3, 4])

In [27]:
#Arange allows for a stepsize
arr2_stepsize = np.arange(1,10,2)
arr2_stepsize

array([1, 3, 5, 7, 9])

In [28]:
#All even numbers between 1 to 10
arr2_stepsize = np.arange(2,10,2)
arr2_stepsize

array([2, 4, 6, 8])

In [31]:
#Numpy allows fractional step sizes
#Difference range vs np.arange -> Fractional step size is allowed
np.arange(1,5,0.1) # Arange allows for floating point step 

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

# Floating Point

In [37]:
arr4 = np.array([1,2,3,4])
print(arr4)
#Notice that in numpy arrays, all elements will have same data type: here it is float
# "int" is raised to "float" for numpy array
arr5= np.array([1,2,3,4.5])
print(arr5) 
#Doesen't happen with python list
l4 = [1,2,3,4.5]
print(l4)

[1 2 3 4]
[1.  2.  3.  4.5]
[1, 2, 3, 4.5]


In [42]:
#We can try to force the datatype if possible, else it would throw an error
arr5 = np.array([1,2,3,4,5],dtype="float")
arr5

array([1., 2., 3., 4., 5.])

In [43]:
type(arr5)

numpy.ndarray

In [45]:
# By default np.array is an n dimension array
arr5.shape

(5,)

# Indexing 

In [52]:
m1 =np.arange(12)
m1
#The indexing similar to list
m1 = np.array([100,200,300,400,500,600])
#We can give list of indices instead of an index too
print(m1[[0,1]])
print(m1[[0,5]])
#We can keep repeating the index
print(m1[[2,3,4,1,2,2]])

[100 200]
[100 600]
[300 400 500 200 300 300]


# Slicing

In [56]:
m1 =np.arange(1,11)
print(m1[:5])
print(m1[-5:-1])



[1 2 3 4 5]
[6 7 8 9]


# Fancy indexing

In [60]:
# If we want to find indexes based on values
# 1,2,3,4,5,6 -> Detractors | 9,10 -> Promoters
m1 = np.array([1,2,3,4,5,6,7,8,9,10])
# This simple indication gives us true or false
m1<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [69]:
#We get those values which are detractors
print(m1[m1<=6])
#Even values
print(m1[m1%2==0])
#Odd values
print(m1[m1%2!=0])

[1 2 3 4 5 6]
[ 2  4  6  8 10]
[1 3 5 7 9]
