In [1]:
5 + 7

12

In [ ]:
# The first thing is to install

In [2]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python3 -m pip install --upgrade pip


In [3]:
# Import statement

import numpy as np

In [4]:
# What is the most basic data structure in Python?
# List

a = [1, 2, 3, 4, 5]

In [5]:
a**2 # Will this work?

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Conclusion: For list ** operation does not work if I want to square

In [6]:
[i**2 for i in a]

[1, 4, 9, 16, 25]

In [7]:
# We will use numpy "array"
a = np.array([1, 2, 3, 4, 5])

In [8]:
type(a)

numpy.ndarray

In [9]:
a

array([1, 2, 3, 4, 5])

## Why Numpy instead of list

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
l = range(1000000)

In [16]:
%timeit [i**2 for i in l]

181 ms ± 815 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [18]:
a**2 # For numpy array, this will square everything

array([ 0,  1,  4,  9, 16])

In [19]:
l = np.arange(1000000)

In [21]:
%timeit l**2

448 µs ± 18.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
# Millisecond of list became microsecond for numpy

## Arange

In [22]:
arr2 = np.arange(1, 5) # last element is excluded
arr2

array([1, 2, 3, 4])

In [27]:
# Arange allows for a stepsize
arr2_stepsize = np.arange(1, 10, 2)
arr2_stepsize

array([1, 3, 5, 7, 9])

In [28]:
# range Vs np.arange - fractional step size is allowed
np.arange(1, 5, 0.1) # arange allows for floating point step

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

## Floating point

In [29]:
arr4 = np.array([1, 2, 3, 4])
arr4

array([1, 2, 3, 4])

In [35]:
arr4 = np.array([1, 2, 3, 4.5])
arr4

array([1. , 2. , 3. , 4.5])

In numpy array, all elements will have same data type: here it is float

In [33]:
# Python list
l4 = [1, 2, 3, 4.5]
l4

[1, 2, 3, 4.5]

"int" is raised to "float" for numpy array

It is possible to force datatype of purely intergers to float also

In [37]:
arr5 = np.array([1, 2, 3, 4])
arr5

array([1, 2, 3, 4])

In [38]:
arr5 = np.array([1, 2, 3, 4], dtype="float")
arr5

array([1., 2., 3., 4.])

In [39]:
type(arr5)

numpy.ndarray

In [40]:
arr5.shape

(4,)

In [ ]:
[6, 7, 5, 9, 5, 6, 7, 8, 6, 7, 9, 10, 9, 7]

# Indexing and slicing

In [41]:
m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
m1[0]

0

In [43]:
m1[5]

5

In [44]:
m1[-1]

11

List of indices

In [45]:
m1 = np.array([100,200,300,400,500,600])

In [47]:
m1[[0, 5]]

array([100, 600])

In [48]:
m1[[2,3,4,1,2,2]]

array([300, 400, 500, 200, 300, 300])

## Slicing

In [50]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
m1[:5]

array([1, 2, 3, 4, 5])

In [52]:
m1[-5:-1]

array([6, 7, 8, 9])

# Fancy Indexing

In [54]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1 < 6 # True or false in each location of the array

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [58]:
m1 [m1 > 4]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
# All the even values from m1?
m1%2 == 0 # modulus (remainder after dividing by 2 = 0)

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [60]:
m1[m1%2==0] # get all even numbers

array([ 2,  4,  6,  8, 10])

In [61]:
m1[m1%2==1] # get all odd numbers

array([1, 3, 5, 7, 9])

In [64]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# NPS

In [69]:
score = np.loadtxt("survey.txt", dtype="int")

In [70]:
score[0]

7

In [71]:
score[1]

10

In [72]:
score.shape

(1167,)

In [73]:
len(score)

1167

In [80]:
total = len(score)
total

1167

In [ ]:
# How to get all the detractors

In [75]:
detractors = score[score <= 6]

In [76]:
promoters = score[score >= 9]

In [78]:
num_detractors = len(detractors)
num_detractors

332

In [79]:
num_promoters = len(promoters)
num_promoters

609

In [83]:
percentage_detractors = (num_detractors/total) * 100
percentage_detractors

28.449014567266495

In [84]:
percentage_promoters = (num_promoters/total) * 100
percentage_promoters

52.185089974293064

In [85]:
nps = percentage_promoters - percentage_detractors
nps

23.73607540702657

# Minimum, maximum, mean

In [86]:
score.min()

1

In [87]:
score.max()

10

In [89]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a[:5] = 100

In [92]:
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])